---
Description: Backend API server

Parameters:
  AMI:
    Type: String
    Default: ami-0d058fe428540cd89
    Description: The Ubuntu AMI to use.
  GitUrl:
    Type: String
    Default: "https://github.com/cyee02/pet-app-api.git"
    Description: Git repo to clone from
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: Enter instance size. Default is t2.micro.
  Key:
    Type: String
    Default: key
    Description: The key used to access the instance.
  MyIP:
    Type: String
    Default: 218.212.92.100/32
    Description: Your IP address to restrict SSH to instance
  NodeVersion:
    Type: String
    Default: "16"
    Description: Node version to run
  SubnetId:
    Type: String
    Default: subnet-0352da80110c23eb8
    Description: Subnet to deploy the instance
  VpcId:
    Type: String
    Default: vpc-0674385a9b9c33c99
    Description: VPC to deploy the instance

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for backend-api'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: 'Allow SSH only from my IP'
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:  !Ref MyIP
        - Description: 'HTTP api request'
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp:  0.0.0.0/0
        - Description: 'HTTPs api request'
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp:  0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref Server

  ServerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "backend-api"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "DynamodbPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              Resource: "*"
        - PolicyName: "S3Policy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:Put*
              - s3:Get*
              - s3:Describe*
              Resource: "*"

  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles: 
        - !Ref ServerRole

  Server:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref ServerInstanceProfile
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref Key
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: |
            Content-Type: text/x-shellscript

            #!/bin/bash
            set -ex

            echo "=== Begin Userdata ==="
            sudo apt-get update

            # Install Node
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
            source ~/.bashrc
            nvm install ${NodeVersion} -y

            # Clone repo
            sudo apt-get install git -y
            git clone ${GitUrl}
            cd ~/pet-app-api
            npm install

            # Set up nginx
            sudo apt-get install nginx -y
            sudo rm /etc/nginx/sites-enabled/default
            sudo cp ~/pet-app-api/staging/nginx_config /etc/nginx/sites-available/pet-app-api
            sudo ln -s /etc/nginx/sites-available/pet-app-api /etc/nginx/sites-enabled/pet-app-api
            sudo /etc/init.d/nginx start

            # Start server
            npm start

            echo "=== End Userdata - SUCCESS ==="

