---
Description: S3 and DynamoDB

Parameters:
  ImageBucketName:
    Type: String
    Default: bucket
    Description: Bucket for storage
  DynamoDBLoginTable:
    Type: String
    Default: login
    Description: DynamoDB table containing login information
  DynamoDBUserTable:
    Type: String
    Default: user
    Description: DynamoDB table containing user information
  DynamoDBMessageTable:
    Type: String
    Default: messages
    Description: DynamoDB table mapping chat id to messages
  DynamoDBConversationTable:
    Type: String
    Default: conversation
    Description: DynamoDB table containing user's messages
  DynamoDBProfileTable:
    Type: String
    Default: profile
    Description: DynamoDB table containing user's public information

Resources:
  LoginTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      TableName:
        Ref: DynamoDBLoginTable

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      TableName:
        Ref: DynamoDBUserTable

  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: conversationId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: conversationId
          KeyType: HASH
      TableName:
        Ref: DynamoDBMessageTable

  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      TableName:
        Ref: DynamoDBConversationTable

  ProfileTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: username
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: username
          KeyType: HASH
      TableName:
        Ref: DynamoDBProfileTable

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      AccessControl: PublicRead
      BucketName:
        Ref: ImageBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:
        Ref: Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicListGet
            Effect: Allow
            Principal: "*"
            Action:
              - s3:List*
              - s3:Get*
            Resource:
                - Fn::Join: [ "", [ Fn::GetAtt: [ Bucket, Arn ], "/users/*" ] ]
